### ISSUE TITLE
"CopyFileA" [ FAILED ]

### ISSUE THREAD

**Issue by ggg4566** [ORCx41/AtomPePacker#3]
[i] Reading " mimi.exe " ...
[i] 64-PE Input Detected ... [ SUPPORTED ]
[i] Generating Exe Output ...
[!] "CopyFileA" [ FAILED ]      3

**Comment by ORCx41** [comment]
can u show more details ??
are you compiling from source code, or using the release ?

**Comment by pentest01** [comment]
Using the release.

**Comment by pentest01** [comment]
![B8B25815-B04A-4F82-937E-C979D88251E9](https://user-images.githubusercontent.com/103268912/195971999-9db26205-3495-4744-850b-6b3832c7ca6b.jpeg)

**Comment by ORCx41** [comment]
can u show me whats inside "C:\Users\Operator\Downloads\Release\Modules"

**Comment by hawaii67** [comment]
Same problem here.
![grafik](https://user-images.githubusercontent.com/13915596/195976651-336be31b-f163-4cd2-aa9e-0d42904dc2ce.png)

**Comment by ORCx41** [comment]
@hawaii67 what is the full path to these files

**Comment by ggg4566** [comment]
> can u show more details ?? are you compiling from source code, or using the release ?

the same error

**Comment by hawaii67** [comment]
Oh, I see your point. Is the path hardcoded?
If I remove everything to 

C:\Users\USER\Downloads\Release>

I get:

>PePacker.exe mimikatz.exe

[i] Reading " mimikatz.exe " ...
[i] 64-PE Input Detected ... [ SUPPORTED ]
[i] Generating Exe Output ...
[i] Reading The Loader "PP64Stub.exe" ... [ DONE ]
[i] Packing ...  [ DONE ]
[+] Compressed Ratio : 39%
[+] Final Pe Size : 532279

and then a crash appears.........

It happens with downloaded release as well as with compiled binary.

**Comment by ggg4566** [comment]
Okay,I compile static binary from source code and work well on win server 2016 and win 10 ,but crash on win7 , win defender can detected :)not affect dump
<img width="929" alt="image" src="https://user-images.githubusercontent.com/7532477/195988979-b273b5c4-62c0-4913-ba66-0eb90010f14b.png">
<img width="683" alt="image" src="https://user-images.githubusercontent.com/7532477/195989241-bc80e77a-1235-46eb-8103-5e34336ebcd1.png">
